### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by KomaGR** [FPBench/FPBench#102]
Hi, there. Thanks for making this project available. It is not clear whether the project is under a license.
If it is not, the project cannot be safely used in other projects (open source or commercial).

Please consider choosing a license and stating it clearly here on GitHub (e.g., adding a `LICENSE` file). This website provides introductions to the various popular licences: https://choosealicense.com/.

**Comment by pavpanchekha** [comment]
Just to clarify—I did see this and will start on it once I'm back from vacation. You're not shouting into the void!

**Comment by pavpanchekha** [comment]
Hi @KomaGR, just to update you on this, we've decided to relicense FPBench under the MIT license. However, this will take a while, because we need to contact all contributors and get their permission. I'll use this issue to track our progress.

**Comment by pavpanchekha** [comment]
Hello! We are working to relicense the FPBench benchmarks and tools under the MIT license. This will make it easier for industrial collaborators and partners to use FPBench and help grow the project. We are looking to license the entire repository as of commit 2419b3c69310311023f20ca906692b8728d9aa6a, not including the `papers/` repository. If you contributed to FPBench, your username is listed below:

- [ ]  @bksaiki
- [ ] @pavpanchekha 
- [ ] @DavidThien 
- [ ] @billzorn 
- [ ] @monadius 
- [ ] @ztatlock 
- [ ] @ndamouche 
- [ ] @HazardousPeach 
- [ ] @IanBriggs 
- [ ] @robertbastian
- [ ] @bmkessler
- [ ] @sorawee 
- [ ] @HeikoBecker 
- [ ] @mmartel66 

If you are named above, please leave a comment below indicating that you agree to have all of your contributions to the FPBench/FPBench repo licensed under an MIT license. (If you do not wish to relicense, or have concerns or questions, please get in touch with me at pavpan@cs.utah.edu)

**Comment by pavpanchekha** [comment]
I agree to relicense all of my contributions to the FPBench/FPBench repository, as of commit 2419b3c and not including the `papers/` repository, under an MIT license.

**Comment by sorawee** [comment]
I agree to relicense all of my contributions to the FPBench/FPBench repository, as of commit 2419b3c and not including the papers/ repository, under an MIT license.

**Comment by robertbastian** [comment]
I agree to relicense all of my contributions to the FPBench/FPBench repository, as of commit 2419b3c and not including the papers/ repository, under an MIT license.

**Comment by monadius** [comment]
I agree to relicense all of my contributions to the FPBench/FPBench repository, as of commit [2419b3c](https://github.com/FPBench/FPBench/commit/2419b3c69310311023f20ca906692b8728d9aa6a) and not including the papers/ repository, under an MIT license.

**Comment by IanBriggs** [comment]
Agreed.

**Comment by bksaiki** [comment]
I agree to relicense all of my contributions to the FPBench/FPBench repository, as of commit 2419b3c and not including the papers/ repository, under an MIT license.

**Comment by DavidThien** [comment]
I agree to relicense all of my contributions to the FPBench/FPBench repository, as of commit 2419b3c and not including the papers/ repository, under an MIT license.

**Comment by billzorn** [comment]
I agree. Formally:

I agree to relicense all of my contributions to the FPBench/FPBench repository, as of commit 2419b3c and not including the papers/ repository, under an MIT license.

**Comment by ztatlock** [comment]
I agree to relicense all of my contributions to the FPBench/FPBench repository, as of commit 2419b3c and not including the papers/ repository, under an MIT license.

**Comment by HeikoBecker** [comment]
I agree to relicense all of my contributions to the FPBench/FPBench repository, as of commit 2419b3c and not including the `papers/` repository, under an MIT license.

**Comment by HazardousPeach** [comment]
I agree to relicense all of my contributions to the FPBench/FPBench repository, as of commit 2419b3c and not including the papers/ repository, under an MIT license.

**Comment by mmartel66** [comment]
I agree to relicense all of my contributions to the FPBench/FPBench repository, as of commit 2419b3c and not including the papers/ repository, under an MIT license.Provide an open source license

**Comment by Damouche** [comment]
I agree to relicense all of my contributions to the FPBench/FPBench repository, as of commit 2419b3c and not including the papers/ repository, under an MIT license.

**Comment by bmkessler** [comment]
I agree to relicense all of my contributions to the FPBench/FPBench repository, as of commit 2419b3c and not including the papers/ repository, under an MIT license.

**Comment by pavpanchekha** [comment]
All of the code at the current repo is now licensed under the MIT license.
