### ISSUE TITLE
execution error when using condition filter or C exporter

### ISSUE THREAD

**Issue by meshsec** [FPBench/FPBench#14]
Hi, thanks a lot for providing such awesome benchmarks and testing framework!
When I download the code and run the commands described in http://fpbench.org/tools.html, I always get this error:
tools/common.rkt:6:23: string-prefix?: unbound identifier in module
  in: string-prefix?
  context...:
   standard-module-name-resolver
   standard-module-name-resolver

I am so sorry for not familiar with racket at all. So ... can you please help me get rid of this error? Thanks in advance:)

**Comment by ztatlock** [comment]
Hi!  Thanks for checking out FPBench :)

What version of Racket are you on?  We've tried to keep things highly compatible, but may have missed a corner case.

**Comment by meshsec** [comment]
Dear ztatlock,
Thank you so much for the response. I fixed the error by changing the racket version :). Now it's v6.11.

Best
