### ISSUE TITLE
Both make sanity  and make test is failing

### ISSUE THREAD

**Issue by santoshn** [FPBench/FPBench#42]
I cloned the version of FPBench and tried to test the repository. Both make sanity and make test seems to be failing on an Ubuntu machine with Racket v6.3. If FPBench needs the latest version or an appropriate version of Racket, it would be helpful to add to the README.

make sanity fails with the following error message:

cat tests/sanity*.fpcore | racket tools/filter.rkt precision binary64 \
| racket tools/filter.rkt not-operators "fma" "!=" "isfinite" "isnormal" "signbit" "exp2" "erf" "erfc" "tgamma" "lgamma" "fmod" "remainder" "fdim" "copysign" "nearbyint" \
| racket infra/test-core2js.rkt --repeat 1
/bin/sh: 1: node: not found
match: no matching clause for ""
  context...:
   /usr/share/racket/collects/racket/match/runtime.rkt:22:0: match:error
   /home/santosh/fpbench/FPBench/infra/test-core2js.rkt:22:0: run<-js
   /home/santosh/fpbench/FPBench/infra/test-core2js.rkt:69:9: for-loop
   /home/santosh/fpbench/FPBench/infra/test-core2js.rkt:63:5: for-loop
   /usr/share/racket/collects/racket/cmdline.rkt:179:51
   (submod /home/santosh/fpbench/FPBench/infra/test-core2js.rkt main): [running body]
Makefile:23: recipe for target 'sanity' failed

Similarly, make test fails with the following error message:

raco test: "./infra/test-imp2core.rkt"
tools/canonicalizer.rkt:94:58: index-where: unbound identifier in module
  in: index-where
Makefile:48: recipe for target 'test' failed
make: *** [test] Error 1

I also noticed that core2c converter fails with the precimonious benchmark with the following error message:

racket tools/core2c.rkt < benchmarks/precimonious.fpcore  > precimonious.c
match: no matching clause for '(! :precision binary32 2)
  context...:
   /usr/share/racket/collects/racket/match/runtime.rkt:22:0: match:error
   /home/santosh/fpbench/FPBench/tools/core2c.rkt:101:5: for-loop
   /usr/share/racket/collects/racket/match/compiler.rkt:410:15: parse-loop285
   /home/santosh/fpbench/FPBench/tools/core2c.rkt:80:5: for-loop
   /usr/share/racket/collects/racket/match/compiler.rkt:410:15: parse-loop227
   /home/santosh/fpbench/FPBench/tools/core2c.rkt:112:5: for-loop
   /usr/share/racket/collects/racket/match/compiler.rkt:410:15: parse-loop285
   /home/santosh/fpbench/FPBench/tools/core2c.rkt:142:6
   /usr/share/racket/collects/racket/port.rkt:125:0: with-output-to-string
   /home/santosh/fpbench/FPBench/tools/core2c.rkt:132:0: core->c14
   /usr/share/racket/collects/racket/cmdline.rkt:179:51
   (submod /home/santosh/fpbench/FPBench/tools/core2c.rkt main): [running body]

Any suggestions on how to fix these?

**Comment by pavpanchekha** [comment]
Hi Santosh! There are several different errors here.

- `make sanity` sanity checks, among other things, the JS compiler. It's complaining that it can't find the `node` command, in other words, NodeJS it not installed. I wouldn't worry too much about that if you're not interested in JS compilation.
- `make test` is failing because it relies on the `index-where` Racket function, which was added in 6.7.0.3, so at least that version is necessary. Racket 6.3 is quite old—I assume you're running Ubuntu Xenial (16.04)? The latest Ubuntu LTS (if you can upgrade) packages 6.11.
- Finally, the C compiler hasn't yet been updated to support multi-precision FPCores—we're working on it—so the last one is a known bug.

**Comment by billzorn** [comment]
The tests have been updated to check for all backends, except for C. This should be further improved:

- [ ] also check for C

- [ ] emit warning messages when tests are skipped

**Comment by DavidThien** [comment]
@santoshn Did this fix your issue?
