### ISSUE TITLE
Support for mixed-precision benchmarks

### ISSUE THREAD

**Issue by oleks** [FPBench/FPBench#5]
Is someone working on [this](https://github.com/FPBench/FPBench/blob/master/papers/nsv16/conclusion.tex#L26)?

**Comment by pavpanchekha** [comment]
We'd like to do it, but right now we don't have examples of benchmarks where we need it. Do you have any particular examples in mind?

**Comment by pavpanchekha** [comment]
The Dagstuhl on Analyzing and Synthesizing Floating-point Programs was really productive toward this. Here's my summary of current thoughts on the mailing list:

https://mailman.cs.washington.edu/pipermail/fpbench/2017-August/0000.html
