### ISSUE TITLE
Website example doesn't run

### ISSUE THREAD

**Issue by IanBriggs** [FPBench/FPBench#55]
On the fpbench website there is a tutorial for exporting fpcore to other languages [here](http://fpbench.org/tools.html)

The example says to run:
> racket export.rkt salsa.fpcore salsa.c

The file salsa.fpcore has been moved to benchmarks/salsa.fpcore, which is easy to figure out, but when running the fixed command a slightly cryptic error is thrown
```
match: no matching clause for '(while* (< t 1000) ((delta_dl 0 (* c sl)) (delta_dr 0 (* c sr)) (delta_d 0 (* (+ delta_dl delta_dr) 1/2)) (delta_theta 0 (* (- delta_dr delta_dl) inv_l)) (arg 0 (+ theta (* delta_theta 1/2))) (cosi 0 (+ (- 1 (* (* arg arg) 1/2)) (* (* (* (* arg arg) ar...
  location...:
   src/core2c.rkt:77:2
  context...:
   /usr/racket/collects/racket/match/runtime.rkt:24:0: match:error
   /home/ibriggs/FPBench/src/core2c.rkt:144:6
   /usr/racket/collects/racket/port.rkt:132:0: with-output-to-string
   /home/ibriggs/FPBench/src/core2c.rkt:134:0: core->c
   ...cket/cmdline.rkt:191:51
   (submod "/home/ibriggs/FPBench/export.rkt" main): [running body]
   temp37_0
   for-loop
   run-module-instance!125
```

The salsa.fpcore file uses while*, which the c exporter doesn't support.

I suggest changing the file used in the example to one of the following, which can be exported using the c exporter:
* benchmarks/fptaylor-extra.fpcore
* benchmarks/fptaylor-real2float.fpcore
* benchmarks/fptaylor-tests.fpcore
* benchmarks/hamming-ch3.fpcore
* benchmarks/herbie.fpcore
* benchmarks/rosa.fpcore
* benchmarks/rump.fpcore

**Comment by pavpanchekha** [comment]
Great catch. Ultimately we need to improve the exporters but I've changed it to the Rump example for now.
