### ISSUE TITLE
Compiling to C for the Precimonius benchmarks crashes 

### ISSUE THREAD

**Issue by vsahil** [FPBench/FPBench#56]
I tried compiling the file "precimonous.fpcore" inside the `benchmarks` directory to C code with racket version 7.4 and it crashed.

**Comment by pavpanchekha** [comment]
Hi @vsahil! You're right—we haven't updated the C compiler with support for annotations. We should at least add an error message instead of crashing.

**Comment by jtarango** [comment]
I am seeing a similar issue.
[jtarango] $ racket export.rkt benchmarks/precimonious.fpcore precimonious.c
match: no matching clause for '(let* ((dppi PI) (h (/ dppi n)) (t1 0)) (while* (<= i n) ((t2 0 (let ((x (* i h))) (while* (<= k 5) ((d1 (! :precision binary32 1) (! :precision binary32 (* d1 2))) (t1 x (+ t1 (/ (sin (* d1 x)) d1))) (k (! :precision integer 1) (! :precision integer (...
  location...:
   src/core2c.rkt:77:2
  context...:
   /usr/share/racket/collects/racket/match/runtime.rkt:24:0: match:error
   /home/jtarango/FPBench/src/core2c.rkt:144:6
   /usr/share/racket/collects/racket/port.rkt:132:0: with-output-to-string
   /home/jtarango/FPBench/src/core2c.rkt:134:0: core->c
   ...cket/cmdline.rkt:179:51
   (submod /home/jtarango/FPBench/export.rkt main): [running body]

[jtarango] $ racket export.rkt benchmarks/salsa.fpcore salsa.c
match: no matching clause for '(while* (< t 1000) ((delta_dl 0 (* c sl)) (delta_dr 0 (* c sr)) (delta_d 0 (* (+ delta_dl delta_dr) 1/2)) (delta_theta 0 (* (- delta_dr delta_dl) inv_l)) (arg 0 (+ theta (* delta_theta 1/2))) (cosi 0 (+ (- 1 (* (* arg arg) 1/2)) (* (* (* (* arg arg) ar...
  location...:
   src/core2c.rkt:77:2
  context...:
   /usr/share/racket/collects/racket/match/runtime.rkt:24:0: match:error
   /home/jtarango/FPBench/src/core2c.rkt:144:6
   /usr/share/racket/collects/racket/port.rkt:132:0: with-output-to-string
   /home/jtarango/FPBench/src/core2c.rkt:134:0: core->c
   ...cket/cmdline.rkt:179:51
   (submod /home/jtarango/FPBench/export.rkt main): [running body]

**Comment by bksaiki** [comment]
This was (sort of) fixed in #60 with the implementation of a supported struct that allows the tester and exporter to reject cores with unsupported precisions. Once the 1.2-support branch is finished, unsupported rounding modes will also be rejected. This issue should be closed after that.

**Comment by billzorn** [comment]
This should be fixed for good in #68
