### ISSUE TITLE
Speed up CakeML floating-point roundtripping/ constants

### ISSUE THREAD

**Issue by HeikoBecker** [FPBench/FPBench#63]
In CakeML, every floating-point parse has to go through the FFI (`Double.toString` and `Double.fromString`).
To speed up the process, one can for known constants create the word from integer constants:
    
    val _ = print (Int.toString (Word64.toInt (Double.fromString "2.0")));

The code above will print an integer representation of the double constant `2.0` to stdout which can then be used in another file with 

     val v = Word64.fromInt <printedConstant>;

**Comment by bksaiki** [comment]
Thanks, Heiko for bringing this up. The CakeML tests actually already passes doubles as integers to the tester as a way of bypassing the Double.toString function. This was mentioned in #62 by @billzorn, but it was implemented for a different reason.
