### ISSUE TITLE
Cleaner separation between "sanity" and "tests"

### ISSUE THREAD

**Issue by billzorn** [FPBench/FPBench#66]
It might be valuable to have a somewhat standardized interface for all of the sanity tests, so that other tools that want to use the test suite know what to expect. Here's my proposal:

"santiy" tests (those in files in tests/ that start with the word "sanity") exercise the most basic functionality of the language in a way that is easy to measure. All sanity tests should:
- be nullary (take no arguments)
- only compute with simple, exactly representable numbers (like 0, 1, or -1.5, never 0.1 or PI) so their behavior is largely unaffected by precision
- provide the expected result as a literal in their :spec property.
- test one feature at a time (we don't want a test for let* to fail because PI isn't supported as a constant)

The goal of sanity tests is to provide a fast to run, easy to understand check on basic functionality, not to identify small inaccuracies or tricky edge cases. If a sanity test fails, then that feature is almost certainly either unsupported or badly broken; conversely, though, sanity tests provide little evidence of correctness.

"test" tests (contained in other files under tests/ that start with the word "test") exercise basic functionality, but not in such a confined way that a literal :spec can be provided. Tests can, and should:
- take inputs
- exercise more advanced functionality, like rounding contexts and preconditions
- check for edge cases

The goal of tests is to compare the behavior of tools in more detail, including their particular quirks and edge cases. We might want to add some sort of flag for "optional" compliance tests that are allowed to fail for some compilers.

All tests, sanity or otherwise, should be labeled as clearly as possible with a :name property and sequence number so that it is clear in the output from the Makefile tests what is going on when one of them fails.

**Comment by pavpanchekha** [comment]
I like this proposed separation. Maybe just have `tests/sanity/` instead of going by file names?

**Comment by billzorn** [comment]
Yes, that is a better idea.

**Comment by billzorn** [comment]
This is effectively done, with the completion of the new exhaustive test generator.

There is more that could be done to improve testing, but this piece of it has been covered.
