### ISSUE TITLE
Scala compiler broken

### ISSUE THREAD

**Issue by pavpanchekha** [FPBench/FPBench#73]
A bug report from our friends at MPI @malyzajko:

1) I have installed Racket and FPBench and tried to run (according to 
the website):
racket export.rkt benchmarks/rump.fpcore rump.scala

This produces an error:

```
supported-list: arity mismatch;
  the expected number of arguments does not match the given number
   expected: 4
   given: 3
   arguments...:
    '(while* while let* let if ! signbit isnormal isnan isinf isfinite 
not or and ...
    '(FALSE TRUE NAN INFINITY HUGE_VAL MAXFLOAT SQRT1_2 SQRT2 M_2_SQRTPI 
M_2_PI M_...
    '(binary32 binary64)
   context...:
    /Applications/Racket v7.7/collects/racket/cmdline.rkt:191:51
    (submod "/Users/eva/Code/FPBench/export.rkt" main): [running body]
    temp35_0
    for-loop
    run-module-instance!
```

Looks like we didn't update the supported tuple in the Scala compiler. How come our tests didn't catch this?

**Comment by bksaiki** [comment]
I actually found this bug in a soon-to-be-merged branch containing testing scripts for the export and transform tools. While we might may not have a scala tester anytime soon, it'll be good to be able to test whether the export tool doesn't break.
