### ISSUE TITLE
Scala exporter does not support ! annotations

### ISSUE THREAD

**Issue by rodalfus** [FPBench/FPBench#78]
When running `racket export.rkt benchmarks/fptaylor-extra.fpcore extra.scala` under Racket v7.7, the following error is thrown:

```
match: no matching clause for '(! :precision binary64 (/ t (! :precision binary32 (+ t 1))))
  location...:
   src/core2scala.rkt:70:2
  context...:
   /Applications/Racket/collects/racket/match/runtime.rkt:24:0: match:error
   /Applications/Racket/collects/racket/match/compiler.rkt:507:40: f166
   /Users/robert/iCloudDrive/uni/BT/FPBench/src/core2scala.rkt:157:4
   /Applications/Racket/collects/racket/port.rkt:132:0: with-output-to-string
   /Users/robert/iCloudDrive/uni/BT/FPBench/export.rkt:80:3: for-loop
   ...cket/cmdline.rkt:191:51
   (submod "/Users/robert/iCloudDrive/uni/BT/FPBench/export.rkt" main): [running body]
   temp35_0
   for-loop
   run-module-instance!
```

Removing the following benchmark from `benchmarks/fptaylor-extra.fpcore` leads to the issue no longer manifesting itself:

```
 (FPCore (t)
  :name "intro-example-mixed"
  :description "Generated by FPTaylor";  
  :precision binary32
  :pre (<= 1 t 999)
  (cast (! :precision binary64 (/ t (! :precision binary32 (+ t 1))))))
```

**Comment by bksaiki** [comment]
Thanks for opening this issue @rodalfus. The scala compiler was trying to match an unsupported operation that should have been filtered out. I have marked '!' and 'cast' as unsupported so it'll exit more gracefully.

Exporting 'fptaylor-extra.fpcore' will now say
`'Sorry, the *.scala exporter does not support !, cast'`

To avoid this, use the filter tool:
`cat benchmarks/fptaylor-extra.fpcore | racket infra/filter.rkt not-operators ! cast | racket export.rkt - extra.scala`

Note that '-' for the export tool tells it to read from stdin.

**Comment by rodalfus** [comment]
Thanks a lot!
