### ISSUE TITLE
Hexadecimal Floating-Point Constants

### ISSUE THREAD

**Issue by monadius** [FPBench/FPBench#8]
I suggest to add hexadecimal floating-point constants with binary exponents (e.g., `0x1.2a4p3`).

It also could be useful to support floating-point constants in the form: `0.1f` (`0.1d`). These numbers should represent closest single (double) precision floating-point numbers to the given real number and they should not introduce any floating-point errors. These definitions are useful because many existing floating-point algorithms use real-valued approximations for exact floating-point constants. For example, constants C1-6 in www.netlib.org/fdlibm/k_cos.c should not introduce any floating-point errors.

**Comment by pavpanchekha** [comment]
Hexadecimal floating-point constants seem like a good addition. Since we're inspired in spirit by SMT-LIB, perhaps `#xABC.DEF` would make sense? Once concern with hex constants is that few languages have simple support for parsing them. OCaml seems to have support (well done!), Scala looks like no, C/++11 and up have support, Racket has partial support, JavaScript does not have enough support. This isn't a huge concern if these constants are rarely used, though—then it is just another uncommonly-supported feature.

**Comment by pavpanchekha** [comment]
For the `0.1f` and `0.1d` constants, this goes back to a discussion we're having on the mailing list, whether FPCore ought to represent purely real-number or floating-point computations. If it is to represent pure-real computations, it is a little strange to be talking about the real number whose value is the closest double-precision number to the real number 0.1. Doubtless, it is a number, but is it too common to reference it?

**Comment by monadius** [comment]
It should be always possible to convert hexadecimal constants to a format which is supported by the target language. You can always convert them to corresponding decimal floating-point constants. It is a strong point of FPBench: it can provide new features to tools and languages.

Constants like `0.1d` are important in some optimized numerical algorithms. I already provided a reference to the `fdlibm` library. You cannot simply replace floating-point constants with corresponding decimal numbers there (write `0.1` instead of `0.1d`). Of course, it is always better to use hexadecimal numbers. But (as you pointed out) hexadecimal numbers are not supported by many programming languages. The following paper presents a method for finding optimal polynomials with floating-point coefficients: https://hal.inria.fr/inria-00119513/fr/. It demonstrates that polynomials with floating-point coefficients are important for evaluating mathematical functions. And these floating-point coefficients cannot be simply replaced with real decimal values.

**Comment by pavpanchekha** [comment]
I agree with the your thoughts on hexadecimal constants. I will try to find some time to implement them in the current tools (Racket does not natively support hex float constants). Hopefully it will be possible to use Racket's libraries to convert to decimal constants.

I understand the uses you're proposing for "rounded" constants, and agree they are valid. We should defer that decision until after the multi-precision discussion gets sorted out on the mailing list—I'll repost your rounded constants idea there.

**Comment by pavpanchekha** [comment]
The FPBench 1.1 draft standard now has support for both hexadecimal constants and explicitly rounded constants (with the `(! :precision binary64 0.1)` construct), so I am closing this issue.
