### ISSUE TITLE
Benchmarks from "Prototype with Apron"

### ISSUE THREAD

**Issue by bibekkabi** [FPBench/FPBench#82]
**https://github.com/bibekkabi/Prototype_analyzerwithApron/tree/master/examples**

FPCore format is ideal, but we can convert from other languages for you in most cases.

**Context**

- https://nsv2020.github.io/, https://www.theses.fr/s239527
- There are few non-linear programs like sine, newton, newton2, square root

**Comment by pavpanchekha** [comment]
Hi Bibek, thanks for the bug report. We'll work on these soon!
