### ISSUE TITLE
Z3 and CakeML compilers incorrectly handle precision annotations in arguments

### ISSUE THREAD

**Issue by monadius** [FPBench/FPBench#93]
```racket
(FPCore ((! :precision binary32 x))
  :description "v should have the same precision as x"
  :precision binary64
  :pre (<= 1 x 20)
  (let ((v x))
    (+ v v)))
```
`core2smtlib2` fails on this example.

`core2cml` returns the following incorrect result:
```sml
fun ex0 (_40__33__32__58_precision_32_binary32_32_x_41_ : word64) = 
  let
    val v = x
  in
    (Double.+ v v)
  end : word64;
```
I am also not sure if the result of `core2go` is correct:
```go
func ex0(x float64) float64 {
	var v = float32(x)
	Use(v)
	return (v + v)
}
```
I think that the type of `x` should be `float32`.

**Comment by HeikoBecker** [comment]
I do not know anything about the Z3 support for floats, but I know that CakeML's floating-point semantics currently can only handle 64-bit double arithmetic. Though it may make sense for `core2cml` to raise an error here, instead of just producing wrong code.

**Comment by bksaiki** [comment]
@HeikoBecker is right, the `core2cml` compiler should just not let you translate that particular program. I think I need to do a careful pass on precision annotations for variables. Sorry, for taking so long on this.
